name: forwarding-discord-telegram
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped
